// <auto-generated />
namespace _2015137308.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100255410_set"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
